10010	WARN	(Cookie No HttpOnly Flag)
10011	WARN	(Cookie Without Secure Flag)
10015	WARN	(Incomplete or No Cache-control Header Set)
10020	FAIL	(X-Frame-Options Header)
10021	FAIL	(X-Content-Type-Options Header Missing)
10038	FAIL	(Content Security Policy Header Not Set)
10054	FAIL	(Cookie without SameSite Attribute)
10202	FAIL	(Absence of Anti-CSRF Tokens)
